apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: test
  POSTGRES_USER: example
  POSTGRES_PASSWORD: example
  PGDATA: /var/lib/postgresql/data/pgdata
