apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-tryout
  template:
    metadata:
      labels:
        app: flask-tryout
    spec:
      containers:
      - name: flask-tryout
        image: a901002666/flask_tryout:latest
        # command: ["sh"]
        env:
          - name: DATABASE_URL
            value: postgresql://example:example@postgres-loadbalancer.default.svc.cluster.local/test
        command: ["python"]
        args: ["-m", "flask", "run", "-h", "0.0.0.0", "-p", "80", "--debugger", "--reload"]
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: flask-tryout

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
# spec:
#   selector:
#     matchLabels:
#       app: nginx
#   replicas: 2 # tells deployment to run 2 pods matching the template
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.14.2
#         ports:
#         - containerPort: 80
