apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-frontend
  labels:
    app: api_frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      frontend: nginx
  template:
    metadata:
      labels:
        frontend: nginx
    spec:
      containers:
      - name: frontend-nginx
        image: nginx:1.19-alpine
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    frontend: nginx
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
