apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress
  # annotations:
  #    kubernetes.io/ingress.class: nginx
spec:
  rules:
  # - host: www.api.rinopower.com
  - http:
      paths:
      - path: /*
        backend:
          serviceName: flask-service
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: site
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
      - rinopower.com
    secretName: rinopower.com
  rules:
  - host: rinopower.com
    http:
      paths:
      # - path: /*
      #   backend:
      #     serviceName: hello-world
      #     servicePort: 60000
      - path: /*
        backend:
          serviceName: flask-service
          servicePort: 80
